/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

/**
 *
 * @author Kenny
 */
public class frm03 extends javax.swing.JFrame {
    /**
     * Creates new form frm03
     */
    public frm03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadioSexo = new javax.swing.ButtonGroup();
        jLabel_CdInfor = new javax.swing.JLabel();
        jLabel_Nome = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Sexo = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jRadioButton_M = new javax.swing.JRadioButton();
        jRadioButton_F = new javax.swing.JRadioButton();
        jLabel_LP = new javax.swing.JLabel();
        jCheckBox_C = new javax.swing.JCheckBox();
        jCheckBox_PHP = new javax.swing.JCheckBox();
        jCheckBox_CS = new javax.swing.JCheckBox();
        jCheckBox_JS = new javax.swing.JCheckBox();
        jCheckBox_J = new javax.swing.JCheckBox();
        jCheckBox_HTML = new javax.swing.JCheckBox();
        jLabel_NivelEs = new javax.swing.JLabel();
        jComboBox_NivelEs = new javax.swing.JComboBox<>();
        jButton1_Gravar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_CdInfor.setText("Cadastro de Informações");

        jLabel_Nome.setText("Nome:");

        jLabel_Email.setText("Email:");

        jLabel_Sexo.setText("Sexo:");

        buttonGroupRadioSexo.add(jRadioButton_M);
        jRadioButton_M.setText("Masculino");
        jRadioButton_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MActionPerformed(evt);
            }
        });

        buttonGroupRadioSexo.add(jRadioButton_F);
        jRadioButton_F.setText("Feminino");

        jLabel_LP.setText("Linguagem de Programação:");

        jCheckBox_C.setText("C");

        jCheckBox_PHP.setText("PHP");

        jCheckBox_CS.setText("C#");

        jCheckBox_JS.setText("JavaScript");
        jCheckBox_JS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_JSActionPerformed(evt);
            }
        });

        jCheckBox_J.setText("Java");

        jCheckBox_HTML.setText("HTML/CSS");

        jLabel_NivelEs.setText("Nível/Escolaridade:");

        jComboBox_NivelEs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médio", "Técnico", "Superior", "Mestrado", "Doutorado" }));

        jButton1_Gravar.setText("Gravar");
        jButton1_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_GravarActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTextArea_Resultado.setColumns(20);
        jTextArea_Resultado.setRows(5);
        jTextArea_Resultado.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea_Resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_Email)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_Email))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_Nome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_Sexo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton_M)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton_F)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_NivelEs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_NivelEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel_CdInfor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1_Gravar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_LP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_CS)
                                .addComponent(jCheckBox_C)
                                .addComponent(jCheckBox_J))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_HTML)
                                .addComponent(jCheckBox_PHP)
                                .addComponent(jCheckBox_JS)))))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_CdInfor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nome)
                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Email)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Sexo)
                    .addComponent(jRadioButton_M)
                    .addComponent(jRadioButton_F))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LP)
                    .addComponent(jCheckBox_C)
                    .addComponent(jCheckBox_PHP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_CS)
                    .addComponent(jCheckBox_JS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_J)
                    .addComponent(jCheckBox_HTML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NivelEs)
                    .addComponent(jComboBox_NivelEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_Gravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MActionPerformed

    private void jCheckBox_JSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_JSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_JSActionPerformed

    private void jButton1_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_GravarActionPerformed
        // TODO add your handling code here:
        jTextArea_Resultado.setText("");
        jTextArea_Resultado.append(" Nome: "+jTextField_Nome.getText());
        jTextArea_Resultado.append("\n\n Email: "+jTextField_Email.getText());
        
        String rbtnTexto = new String();
        if(jRadioButton_M.isSelected() == true){
            rbtnTexto = jRadioButton_M.getText();
        }else if(jRadioButton_F.isSelected() == true){
            rbtnTexto = jRadioButton_F.getText();
        }
        jTextArea_Resultado.append("\n\n Sexo: "+rbtnTexto);
        
        String ckboxTexto = new String();
        if(jCheckBox_C.isSelected() == true){
            ckboxTexto += jCheckBox_C.getText()+", ";
        }
        if(jCheckBox_CS.isSelected() == true){
            ckboxTexto += jCheckBox_CS.getText()+", ";
        }
        if(jCheckBox_HTML.isSelected() == true){
            ckboxTexto += jCheckBox_HTML.getText()+", ";
        }
        if(jCheckBox_J.isSelected() == true){
            ckboxTexto += jCheckBox_J.getText()+", ";
        }
        if(jCheckBox_JS.isSelected() == true){
            ckboxTexto += jCheckBox_JS.getText()+", ";
        }
        if(jCheckBox_PHP.isSelected() == true){
            ckboxTexto += jCheckBox_PHP.getText()+", ";
        }
        jTextArea_Resultado.append("\n\n Linguagens / Interesses: "+ckboxTexto);
        jTextArea_Resultado.append("\n\n Nível / Escolaridade: "+jComboBox_NivelEs.getSelectedItem());
    }//GEN-LAST:event_jButton1_GravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRadioSexo;
    private javax.swing.JButton jButton1_Gravar;
    private javax.swing.JCheckBox jCheckBox_C;
    private javax.swing.JCheckBox jCheckBox_CS;
    private javax.swing.JCheckBox jCheckBox_HTML;
    private javax.swing.JCheckBox jCheckBox_J;
    private javax.swing.JCheckBox jCheckBox_JS;
    private javax.swing.JCheckBox jCheckBox_PHP;
    private javax.swing.JComboBox<String> jComboBox_NivelEs;
    private javax.swing.JLabel jLabel_CdInfor;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_LP;
    private javax.swing.JLabel jLabel_NivelEs;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Sexo;
    private javax.swing.JRadioButton jRadioButton_F;
    private javax.swing.JRadioButton jRadioButton_M;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_Resultado;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Nome;
    // End of variables declaration//GEN-END:variables
}
