/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenny
 */
public class frmMenuVendasCadastradas extends javax.swing.JFrame {
    
    frmMenuSelecaoVendaCadastros enviaInf;
    /**
     * Creates new form frmMenuVendasCadastradas
     */
    public frmMenuVendasCadastradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ClienteC = new javax.swing.JTable();
        jButton_Cadastrar = new javax.swing.JButton();
        jTextField_Cliente = new javax.swing.JTextField();
        jTextField_Empresa = new javax.swing.JTextField();
        jTextField_Tarifa = new javax.swing.JTextField();
        jTextField_Rota = new javax.swing.JTextField();
        jButton_VoltarSelecao = new javax.swing.JButton();
        jButton_IrParaSelecaoVendaCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_ClienteC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLIENTE", "EMPRESA", "ROTA", "TARIFA"
            }
        ));
        jScrollPane2.setViewportView(jTable_ClienteC);

        jButton_Cadastrar.setText("CADASTRAR");
        jButton_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarActionPerformed(evt);
            }
        });

        jTextField_Cliente.setEnabled(false);
        jTextField_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ClienteActionPerformed(evt);
            }
        });

        jTextField_Empresa.setEnabled(false);
        jTextField_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmpresaActionPerformed(evt);
            }
        });

        jTextField_Tarifa.setEnabled(false);

        jTextField_Rota.setEnabled(false);

        jButton_VoltarSelecao.setText("VOLTAR");
        jButton_VoltarSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarSelecaoActionPerformed(evt);
            }
        });

        jButton_IrParaSelecaoVendaCadastro.setText("FIM");
        jButton_IrParaSelecaoVendaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IrParaSelecaoVendaCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_VoltarSelecao)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton_IrParaSelecaoVendaCadastro)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField_Rota, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(jButton_Cadastrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton_Cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Rota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton_IrParaSelecaoVendaCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_VoltarSelecao)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel cadastroP = (DefaultTableModel) jTable_ClienteC.getModel();
        Object[] dados = {jTextField_Cliente.getText(), jTextField_Empresa.getText(), jTextField_Rota.getText(), jTextField_Tarifa.getText()};
        cadastroP.addRow(dados);
        enviaInf = new frmMenuSelecaoVendaCadastros();
        enviaInf.receberCliente(jTextField_Cliente.getText());
        enviaInf.receberEmpresa(jTextField_Empresa.getText());
        enviaInf.receberRota(jTextField_Rota.getText());
        enviaInf.receberTarifa(jTextField_Tarifa.getText());
        jTextField_Cliente.setText("");
        jTextField_Empresa.setText("");
        jTextField_Rota.setText("");
        jTextField_Tarifa.setText("");
    }//GEN-LAST:event_jButton_CadastrarActionPerformed

    private void jTextField_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ClienteActionPerformed

    private void jTextField_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmpresaActionPerformed

    private void jButton_VoltarSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarSelecaoActionPerformed
        // TODO add your handling code here:
        frmMenuSelecaoVendaCadastros selecaoVendaCadastro = new frmMenuSelecaoVendaCadastros();
        selecaoVendaCadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_VoltarSelecaoActionPerformed

    private void jButton_IrParaSelecaoVendaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IrParaSelecaoVendaCadastroActionPerformed
        // TODO add your handling code here:
        //frmMenuSelecaoVendaCadastros selecaoVendaCadastros = new frmMenuSelecaoVendaCadastros();
        //selecaoVendaCadastros.setVisible(true);
        //enviaInf = new frmMenuSelecaoVendaCadastros();
        enviaInf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_IrParaSelecaoVendaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuVendasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuVendasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuVendasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuVendasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuVendasCadastradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JButton jButton_IrParaSelecaoVendaCadastro;
    private javax.swing.JButton jButton_VoltarSelecao;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_ClienteC;
    private javax.swing.JTextField jTextField_Cliente;
    private javax.swing.JTextField jTextField_Empresa;
    private javax.swing.JTextField jTextField_Rota;
    private javax.swing.JTextField jTextField_Tarifa;
    // End of variables declaration//GEN-END:variables
    public void receberCliente(String cliente){
        jTextField_Cliente.setText(cliente);
    }
    
    public void receberEmpresa(String empresa){
        jTextField_Empresa.setText(empresa);
    }
    
    public void receberRota(String origem, String destino){
        jTextField_Rota.setText(origem+"->"+destino);
        
    }
    
    public void receberTarifa(String tarifa){
        jTextField_Tarifa.setText(tarifa);
    }
    
    public void receberRota(String rota){//Recebendo da seleçãoVendaCadastro
        jTextField_Rota.setText(rota);
    }
}
