/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

/**
 *
 * @author Kenny
 */
public class frmMenuConvencional extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuConvencional
     */
    public frmMenuConvencional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ArCondicionado = new javax.swing.JLabel();
        jLabel_Banheiro = new javax.swing.JLabel();
        jLabel_Reclinacao = new javax.swing.JLabel();
        jLabel_Largura = new javax.swing.JLabel();
        jLabel_Distância = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Voltar = new javax.swing.JButton();
        jLabel_122G = new javax.swing.JLabel();
        jLabel_43cm = new javax.swing.JLabel();
        jLabel_67cm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_ArCondicionado.setText("AR-CONDICIONADO");

        jLabel_Banheiro.setText("BANHEIRO");

        jLabel_Reclinacao.setText("RECLINAÇÃO");

        jLabel_Largura.setText("LARGURA");

        jLabel_Distância.setText("DISTÂNCIA");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel1.setText("CONVENCIONAL");

        jButton_Voltar.setText("VOLTAR");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        jLabel_122G.setText("122°");

        jLabel_43cm.setText("43cm");

        jLabel_67cm.setText("67cm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_ArCondicionado)
                        .addComponent(jLabel_Banheiro)
                        .addComponent(jLabel_Reclinacao)
                        .addComponent(jLabel_Largura)
                        .addComponent(jLabel_Distância))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton_Voltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_122G, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_43cm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_67cm, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel_ArCondicionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Banheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reclinacao)
                    .addComponent(jLabel_122G))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Largura)
                    .addComponent(jLabel_43cm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Distância)
                    .addComponent(jLabel_67cm))
                .addGap(46, 46, 46)
                .addComponent(jButton_Voltar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuConvencional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuConvencional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_122G;
    private javax.swing.JLabel jLabel_43cm;
    private javax.swing.JLabel jLabel_67cm;
    private javax.swing.JLabel jLabel_ArCondicionado;
    private javax.swing.JLabel jLabel_Banheiro;
    private javax.swing.JLabel jLabel_Distância;
    private javax.swing.JLabel jLabel_Largura;
    private javax.swing.JLabel jLabel_Reclinacao;
    // End of variables declaration//GEN-END:variables
}
