/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

import static java.awt.Frame.NORMAL;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class frmMenuAssentos01_Rota_02 extends javax.swing.JFrame {
    
    frmMenuInformacoesP enviaInf;
    public int assentosSelec;
    /**
     * Creates new form frmMenuAssentos01_Rota_02
     */
    public frmMenuAssentos01_Rota_02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Reservar = new javax.swing.JButton();
        jLabel_Saoluis_Bacabal_Leito = new javax.swing.JLabel();
        jTextField_ReceberPreco = new javax.swing.JTextField();
        jButton_Voltar = new javax.swing.JButton();
        jLabelApenasUmAssento = new javax.swing.JLabel();
        jTextField_Empresa = new javax.swing.JTextField();
        jTextField_Origem = new javax.swing.JTextField();
        jTextField_Destino = new javax.swing.JTextField();
        jTextField_Tipo = new javax.swing.JTextField();
        jTextField_Horario = new javax.swing.JTextField();
        jTextField_Tarifa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("01");
        jToggleButton1.setEnabled(false);

        jToggleButton2.setText("03");
        jToggleButton2.setEnabled(false);

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("02");

        jToggleButton4.setText("04");
        jToggleButton4.setEnabled(false);

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("05");

        jToggleButton6.setText("06");
        jToggleButton6.setEnabled(false);

        jToggleButton7.setText("13");
        jToggleButton7.setEnabled(false);

        jToggleButton8.setText("14");
        jToggleButton8.setEnabled(false);

        jToggleButton9.setText("15");
        jToggleButton9.setEnabled(false);

        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setText("16");

        jToggleButton11.setText("18");
        jToggleButton11.setEnabled(false);

        buttonGroup1.add(jToggleButton12);
        jToggleButton12.setText("17");

        buttonGroup1.add(jToggleButton13);
        jToggleButton13.setText("22");

        buttonGroup1.add(jToggleButton14);
        jToggleButton14.setText("24");

        jToggleButton15.setText("07");
        jToggleButton15.setEnabled(false);

        jToggleButton16.setText("23");
        jToggleButton16.setEnabled(false);

        buttonGroup1.add(jToggleButton17);
        jToggleButton17.setText("09");

        buttonGroup1.add(jToggleButton18);
        jToggleButton18.setText("08");

        jToggleButton19.setText("10");
        jToggleButton19.setEnabled(false);

        jToggleButton20.setText("11");
        jToggleButton20.setEnabled(false);

        jToggleButton21.setText("12");
        jToggleButton21.setEnabled(false);

        jToggleButton22.setText("19");
        jToggleButton22.setEnabled(false);

        jToggleButton23.setText("20");
        jToggleButton23.setEnabled(false);

        buttonGroup1.add(jToggleButton24);
        jToggleButton24.setText("21");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Selecione o assento");

        jButton_Reservar.setText("RESERVAR");
        jButton_Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReservarActionPerformed(evt);
            }
        });

        jLabel_Saoluis_Bacabal_Leito.setText("SÃO LUÍS (MA) -> BACABAL (MA) / (LEITO)");

        jTextField_ReceberPreco.setEnabled(false);

        jButton_Voltar.setText("VOLTAR");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        jLabelApenasUmAssento.setText("*APENAS UM ASSENTO POR PASSAGEM");

        jTextField_Empresa.setEnabled(false);

        jTextField_Origem.setEnabled(false);

        jTextField_Destino.setEnabled(false);

        jTextField_Tipo.setEnabled(false);

        jTextField_Horario.setEnabled(false);

        jTextField_Tarifa.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField_ReceberPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton_Voltar)
                .addGap(87, 390, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton7))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton4)
                                .addGap(64, 64, 64)
                                .addComponent(jToggleButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton2)
                                .addGap(64, 64, 64)
                                .addComponent(jToggleButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton9)
                                .addGap(64, 64, 64)
                                .addComponent(jToggleButton12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton11)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton18)
                    .addComponent(jToggleButton22)
                    .addComponent(jToggleButton23))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton17)
                        .addGap(64, 64, 64)
                        .addComponent(jToggleButton20)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton13)
                                .addGap(64, 64, 64)
                                .addComponent(jToggleButton14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton24)
                                .addGap(64, 64, 64)
                                .addComponent(jToggleButton16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton19)
                                .addGap(64, 64, 64)
                                .addComponent(jToggleButton21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Horario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Tipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Origem)
                            .addComponent(jTextField_Empresa)
                            .addComponent(jTextField_Destino))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelApenasUmAssento)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(23, 23, 23))
                        .addComponent(jButton_Reservar))
                    .addComponent(jLabel_Saoluis_Bacabal_Leito))
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Saoluis_Bacabal_Leito)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton17)
                    .addComponent(jToggleButton20))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton4)
                            .addComponent(jToggleButton6)
                            .addComponent(jToggleButton18)
                            .addComponent(jToggleButton19)
                            .addComponent(jToggleButton21))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton7)
                            .addComponent(jToggleButton9)
                            .addComponent(jToggleButton12)
                            .addComponent(jToggleButton22)
                            .addComponent(jToggleButton24)
                            .addComponent(jToggleButton16))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton11)
                            .addComponent(jToggleButton10)
                            .addComponent(jToggleButton8)
                            .addComponent(jToggleButton23)
                            .addComponent(jToggleButton13)
                            .addComponent(jToggleButton14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addComponent(jLabelApenasUmAssento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ReceberPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Voltar)
                    .addComponent(jButton_Reservar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReservarActionPerformed
        // TODO add your handling code here:
        enviaInf = new frmMenuInformacoesP();
        String buttonText = new String();
        if(jToggleButton1.isSelected() == true){
            buttonText += jToggleButton1.getText()+" ";
            assentosSelec++;
        }if(jToggleButton10.isSelected() == true){
            buttonText += jToggleButton10.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton11.isSelected() == true){
            buttonText += jToggleButton11.getText()+" ";
            assentosSelec++;
        }if(jToggleButton12.isSelected() == true){
            buttonText += jToggleButton12.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton13.isSelected() == true){
            buttonText += jToggleButton13.getText()+" ";
            assentosSelec++;
        }if(jToggleButton14.isSelected() == true){
            buttonText += jToggleButton14.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton15.isSelected() == true){
            buttonText += jToggleButton15.getText()+" ";
            assentosSelec++;
        }if(jToggleButton16.isSelected() == true){
            buttonText += jToggleButton16.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton17.isSelected() == true){
            buttonText += jToggleButton17.getText()+" ";
            assentosSelec++;
        }if(jToggleButton18.isSelected() == true){
            buttonText += jToggleButton18.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton19.isSelected() == true){
            buttonText += jToggleButton19.getText()+" ";
            assentosSelec++;
        }if(jToggleButton20.isSelected() == true){
            buttonText += jToggleButton20.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton2.isSelected() == true){
            buttonText += jToggleButton2.getText()+" ";
            assentosSelec++;
        }if(jToggleButton21.isSelected() == true){
            buttonText += jToggleButton21.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton22.isSelected() == true){
            buttonText += jToggleButton22.getText()+" ";
            assentosSelec++;
        }if(jToggleButton23.isSelected() == true){
            buttonText += jToggleButton23.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton24.isSelected() == true){
            buttonText += jToggleButton24.getText()+" ";
            assentosSelec++;
        }if(jToggleButton3.isSelected() == true){
            buttonText += jToggleButton3.getText()+" ";
            assentosSelec++;
        }if(jToggleButton4.isSelected() == true){
            buttonText += jToggleButton4.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton5.isSelected() == true){
            buttonText += jToggleButton5.getText()+" ";
            assentosSelec++;
        }if(jToggleButton6.isSelected() == true){
            buttonText += jToggleButton6.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton7.isSelected() == true){
            buttonText += jToggleButton7.getText()+" ";
            assentosSelec++;
        }if(jToggleButton8.isSelected() == true){
            buttonText += jToggleButton8.getText()+" ";
            assentosSelec++;
        }
        if(jToggleButton9.isSelected() == true){
            buttonText += jToggleButton9.getText()+" ";
            assentosSelec++;
        }
        int flag = JOptionPane.showConfirmDialog(null, "Assento: "+buttonText + "\n Tarifa: "+jTextField_Tarifa.getText(), "Confirmar seleção!", NORMAL);
        if(jToggleButton1.isSelected() == true || jToggleButton10.isSelected() == true || jToggleButton11.isSelected() == true || jToggleButton12.isSelected() == true
                || jToggleButton13.isSelected() == true || jToggleButton14.isSelected() == true || jToggleButton15.isSelected() == true || jToggleButton16.isSelected() == true
                || jToggleButton17.isSelected() == true || jToggleButton18.isSelected() == true || jToggleButton19.isSelected() == true || jToggleButton20.isSelected() == true
                || jToggleButton21.isSelected() == true || jToggleButton22.isSelected() == true || jToggleButton23.isSelected() == true || jToggleButton24.isSelected() == true
                || jToggleButton2.isSelected() == true || jToggleButton3.isSelected() == true || jToggleButton4.isSelected() == true || jToggleButton5.isSelected() == true
                || jToggleButton6.isSelected() == true || jToggleButton7.isSelected() == true || jToggleButton8.isSelected() == true || jToggleButton9.isSelected() == true){
            if(flag == 0){//0 == sim
                //frmMenuInformacoesP infP = new frmMenuInformacoesP();
                //infP.setVisible(true);
                enviaInf.receberEmpresa(jTextField_Empresa.getText());
                enviaInf.receberRota(jTextField_Origem.getText(), jTextField_Destino.getText());
                enviaInf.receberTipo(jTextField_Tipo.getText());
                enviaInf.receberHorario(jTextField_Horario.getText());
                enviaInf.receberTarifa(jTextField_Tarifa.getText());
                enviaInf.setVisible(true);
            }

            if(flag == 1){//1 == não
                jButton_Reservar.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "ASSENTO NÃO SELECIONADO!");
            jToggleButton1.requestFocus();
        }  
    }//GEN-LAST:event_jButton_ReservarActionPerformed

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAssentos01_Rota_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAssentos01_Rota_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAssentos01_Rota_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAssentos01_Rota_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuAssentos01_Rota_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Reservar;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApenasUmAssento;
    private javax.swing.JLabel jLabel_Saoluis_Bacabal_Leito;
    private javax.swing.JTextField jTextField_Destino;
    private javax.swing.JTextField jTextField_Empresa;
    private javax.swing.JTextField jTextField_Horario;
    private javax.swing.JTextField jTextField_Origem;
    private javax.swing.JTextField jTextField_ReceberPreco;
    private javax.swing.JTextField jTextField_Tarifa;
    private javax.swing.JTextField jTextField_Tipo;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
    public void recebendoV2(String recebe){
        jTextField_ReceberPreco.setText(recebe);
    }
    
     public void recebendoPreco2(double preco){
        preco *= assentosSelec;
    }
     
//-------------------------------------------------------------------//
    public void receberEmpresa(String empresa){
        jTextField_Empresa.setText("Empresa: "+empresa);
    }
    
    public void receberRota(String origem, String destino){
        jTextField_Origem.setText("Origem: "+origem);
        jTextField_Destino.setText("Destino: "+destino);
    }
    
    public void receberTipo(String tipo){
        jTextField_Tipo.setText("Tipo: "+tipo);
    }
    
    public void receberHorario(String horario){
        jTextField_Horario.setText("Horário: "+horario);
    }
    
    public void receberTarifa(String tarifa){
        jTextField_Tarifa.setText(tarifa);
    }
}
