/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class frmMenuInformacoesP extends javax.swing.JFrame {
    
    frmMenuVendasCadastradas enviarInf;
    
    //public String empresaR;
    //public String origem, destino, tipo, horario, tarifa;
    /**
     * Creates new form frmLogin
     */
    public frmMenuInformacoesP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Confirmacao_e_Dados = new javax.swing.JLabel();
        jLabel_Comprador = new javax.swing.JLabel();
        jLabel_Nome = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_Cpf = new javax.swing.JLabel();
        jTextField_Cpf = new javax.swing.JTextField();
        jTextField_Telefone = new javax.swing.JTextField();
        jLabel_Telefone = new javax.swing.JLabel();
        jLabel_Comprador1 = new javax.swing.JLabel();
        jPanel_Cartao = new javax.swing.JPanel();
        jLabel_NomeTitular = new javax.swing.JLabel();
        jTextField_NomeTitular = new javax.swing.JTextField();
        jLabel_Cpf1 = new javax.swing.JLabel();
        jTextField_Cpf1 = new javax.swing.JTextField();
        jLabel_CEP = new javax.swing.JLabel();
        jTextField_CEP = new javax.swing.JTextField();
        jLabel_NCartao = new javax.swing.JLabel();
        jTextField_NCartao = new javax.swing.JTextField();
        jLabel_CodSeguranca = new javax.swing.JLabel();
        jTextField_CodSeguranca = new javax.swing.JTextField();
        jTextField_DataValidade = new javax.swing.JTextField();
        jLabel_DataValidade = new javax.swing.JLabel();
        jLabel_Parcelas = new javax.swing.JLabel();
        jComboBox_Parcelas = new javax.swing.JComboBox<>();
        jToggleButtonCartaoCredito = new javax.swing.JToggleButton();
        jLabel_Obrigatorio5 = new javax.swing.JLabel();
        jLabel_Obrigatorio7 = new javax.swing.JLabel();
        jLabel_Obrigatorio4 = new javax.swing.JLabel();
        jButton_Validar = new javax.swing.JButton();
        jPanel_Pix = new javax.swing.JPanel();
        jToggleButton_Pix = new javax.swing.JToggleButton();
        jPanel_QRCode = new javax.swing.JPanel();
        jLabel_Qrcode = new javax.swing.JLabel();
        jButton_FinalizarCompra = new javax.swing.JButton();
        jCheckBox_TermoDeUso = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Obrigatorio = new javax.swing.JLabel();
        jLabel_Obrigatorio1 = new javax.swing.JLabel();
        jLabel_Obrigatorio2 = new javax.swing.JLabel();
        jLabel_Obrigatorio3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Empresa = new javax.swing.JTextField();
        jTextField_Destino = new javax.swing.JTextField();
        jTextField_Tipo = new javax.swing.JTextField();
        jTextField_Origem = new javax.swing.JTextField();
        jTextField_Horario = new javax.swing.JTextField();
        jTextField_Tarifa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Confirmacao_e_Dados.setFont(new java.awt.Font("Futura CondensedLight", 1, 18)); // NOI18N
        jLabel_Confirmacao_e_Dados.setText("CONFIRMAÇÃO E DADOS DO PASSAGEIRO");

        jLabel_Comprador.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Comprador.setText("COMPRADOR:");

        jLabel_Nome.setText("Nome:");

        jTextField_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NomeActionPerformed(evt);
            }
        });

        jLabel_Email.setText("E-mail:");

        jLabel_Cpf.setText("CPF:");

        jLabel_Telefone.setText("N° de telefone:");

        jLabel_Comprador1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Comprador1.setText("PAGAMENTO:");

        jPanel_Cartao.setBackground(new java.awt.Color(153, 255, 255));
        jPanel_Cartao.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jLabel_NomeTitular.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NomeTitular.setText("Nome do titular:");

        jTextField_NomeTitular.setEnabled(false);

        jLabel_Cpf1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Cpf1.setText("CPF:");

        jTextField_Cpf1.setEnabled(false);

        jLabel_CEP.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_CEP.setText("CEP da fatura:");

        jTextField_CEP.setEnabled(false);

        jLabel_NCartao.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NCartao.setText("N° do cartão:");

        jTextField_NCartao.setEnabled(false);

        jLabel_CodSeguranca.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_CodSeguranca.setText("Cód de segurança:");

        jTextField_CodSeguranca.setEnabled(false);

        jTextField_DataValidade.setText("mm/aa");
        jTextField_DataValidade.setToolTipText("");
        jTextField_DataValidade.setEnabled(false);

        jLabel_DataValidade.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DataValidade.setText("Data de validade:");

        jLabel_Parcelas.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Parcelas.setText("Parcelas:");

        jComboBox_Parcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 parcela", "2 parcelas", "3 parcelas", "4 parcelas", "5 parcelas", "6 parcelas", "7 parcelas", "8 parcelas", "9 parcelas", "10 parcelas", "11 parcelas", "12 parcelas" }));
        jComboBox_Parcelas.setEnabled(false);

        jToggleButtonCartaoCredito.setText("Cartão de crédito");
        jToggleButtonCartaoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCartaoCreditoActionPerformed(evt);
            }
        });

        jLabel_Obrigatorio5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Obrigatorio5.setText("*Obrigatório");
        jLabel_Obrigatorio5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_Obrigatorio5PropertyChange(evt);
            }
        });

        jLabel_Obrigatorio7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Obrigatorio7.setText("*Obrigatório");
        jLabel_Obrigatorio7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_Obrigatorio7PropertyChange(evt);
            }
        });

        jLabel_Obrigatorio4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Obrigatorio4.setText("*Obrigatório");
        jLabel_Obrigatorio4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_Obrigatorio4PropertyChange(evt);
            }
        });

        jButton_Validar.setText("VALIDAR");
        jButton_Validar.setEnabled(false);
        jButton_Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CartaoLayout = new javax.swing.GroupLayout(jPanel_Cartao);
        jPanel_Cartao.setLayout(jPanel_CartaoLayout);
        jPanel_CartaoLayout.setHorizontalGroup(
            jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jToggleButtonCartaoCredito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_NomeTitular)
                    .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                        .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CodSeguranca)
                            .addComponent(jTextField_CodSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DataValidade)
                            .addComponent(jTextField_DataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel_Parcelas)
                    .addComponent(jComboBox_Parcelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                        .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Cpf1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel_NCartao)
                            .addComponent(jTextField_NomeTitular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_CEP)
                            .addComponent(jTextField_NCartao)
                            .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Cpf1)
                                    .addComponent(jLabel_CEP))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Obrigatorio4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Obrigatorio5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Obrigatorio7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CartaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Validar)
                        .addGap(35, 35, 35))))
        );
        jPanel_CartaoLayout.setVerticalGroup(
            jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonCartaoCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                        .addComponent(jLabel_CEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_NCartao)
                                    .addComponent(jLabel_Cpf1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_NCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Obrigatorio5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_CodSeguranca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CodSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                                .addComponent(jLabel_DataValidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_DataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Obrigatorio7)))))
                    .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                        .addComponent(jLabel_NomeTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_CartaoLayout.createSequentialGroup()
                                .addComponent(jTextField_NomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField_Cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Obrigatorio4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Parcelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Validar)))
        );

        jPanel_Pix.setBackground(new java.awt.Color(153, 255, 255));
        jPanel_Pix.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jToggleButton_Pix.setText("Pix");
        jToggleButton_Pix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_PixActionPerformed(evt);
            }
        });

        jPanel_QRCode.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_QRCode.setForeground(new java.awt.Color(0, 0, 0));

        jLabel_Qrcode.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenny\\Pictures\\qrcode.png")); // NOI18N
        jLabel_Qrcode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_QrcodePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel_QRCodeLayout = new javax.swing.GroupLayout(jPanel_QRCode);
        jPanel_QRCode.setLayout(jPanel_QRCodeLayout);
        jPanel_QRCodeLayout.setHorizontalGroup(
            jPanel_QRCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_QRCodeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Qrcode)
                .addContainerGap())
        );
        jPanel_QRCodeLayout.setVerticalGroup(
            jPanel_QRCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QRCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Qrcode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_PixLayout = new javax.swing.GroupLayout(jPanel_Pix);
        jPanel_Pix.setLayout(jPanel_PixLayout);
        jPanel_PixLayout.setHorizontalGroup(
            jPanel_PixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PixLayout.createSequentialGroup()
                .addGroup(jPanel_PixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PixLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_QRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_PixLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jToggleButton_Pix, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel_PixLayout.setVerticalGroup(
            jPanel_PixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PixLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_QRCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_Pix)
                .addGap(12, 12, 12))
        );

        jButton_FinalizarCompra.setText("FINALIZAR SUA COMPRA");
        jButton_FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FinalizarCompraActionPerformed(evt);
            }
        });

        jCheckBox_TermoDeUso.setText("Ao confirmar a compra eu concordo com os termos de uso e política de privacidade");
        jCheckBox_TermoDeUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_TermoDeUsoActionPerformed(evt);
            }
        });

        jLabel1.setText("*Aguardaremos confirmação do pagamento");

        jLabel_Obrigatorio.setText("*Obrigatório");
        jLabel_Obrigatorio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_ObrigatorioPropertyChange(evt);
            }
        });

        jLabel_Obrigatorio1.setText("*Obrigatório");
        jLabel_Obrigatorio1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_Obrigatorio1PropertyChange(evt);
            }
        });

        jLabel_Obrigatorio2.setText("*Obrigatório");
        jLabel_Obrigatorio2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_Obrigatorio2PropertyChange(evt);
            }
        });

        jLabel_Obrigatorio3.setText("*Obrigatório");
        jLabel_Obrigatorio3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_Obrigatorio3PropertyChange(evt);
            }
        });

        jLabel2.setText("*");

        jTextField_Empresa.setEnabled(false);

        jTextField_Destino.setEnabled(false);

        jTextField_Tipo.setEnabled(false);

        jTextField_Origem.setEnabled(false);

        jTextField_Horario.setEnabled(false);

        jTextField_Tarifa.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox_TermoDeUso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel_Confirmacao_e_Dados)
                        .addGap(130, 130, 130))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel_Pix, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Horario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Tipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Origem)
                            .addComponent(jTextField_Empresa)
                            .addComponent(jTextField_Destino)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel_Comprador1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel_Comprador))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel_Email)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel_Cpf)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel_Telefone)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_Telefone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel_Nome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Obrigatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Obrigatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Obrigatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Obrigatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jButton_FinalizarCompra)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Cartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Confirmacao_e_Dados)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Comprador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nome)
                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Obrigatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Obrigatorio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cpf)
                    .addComponent(jTextField_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Obrigatorio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Telefone)
                    .addComponent(jTextField_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Obrigatorio3))
                .addGap(35, 35, 35)
                .addComponent(jLabel_Comprador1)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Cartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Pix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_TermoDeUso)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton_FinalizarCompra)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_TermoDeUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_TermoDeUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_TermoDeUsoActionPerformed

    private void jLabel_ObrigatorioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_ObrigatorioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ObrigatorioPropertyChange

    private void jLabel_Obrigatorio1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_Obrigatorio1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Obrigatorio1PropertyChange

    private void jLabel_Obrigatorio2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_Obrigatorio2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Obrigatorio2PropertyChange

    private void jLabel_Obrigatorio3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_Obrigatorio3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Obrigatorio3PropertyChange

    private void jButton_FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FinalizarCompraActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        if (jTextField_Nome.getText().length() > 0) {
            jLabel_Obrigatorio.setVisible(false);
        } else {
            jLabel_Obrigatorio.setVisible(true);
        }
        if (jTextField_Email.getText().length() > 0) {
            jLabel_Obrigatorio1.setVisible(false);
        } else {
            jLabel_Obrigatorio1.setVisible(true);
        }
        if (jTextField_Cpf.getText().length() > 0) {
            jLabel_Obrigatorio2.setVisible(false);
        } else {
            jLabel_Obrigatorio2.setVisible(true);
        }
        if (jTextField_Telefone.getText().length() > 0) {
            jLabel_Obrigatorio3.setVisible(false);
        } else {
            jLabel_Obrigatorio3.setVisible(true);
        }
        if ((jTextField_Nome.getText().length()>0)
                &&(jTextField_Email.getText().length()> 0)
                && (jTextField_Cpf.getText().length() > 0) 
                && (jTextField_Telefone.getText().length() > 0)
                && (jCheckBox_TermoDeUso.isSelected() == true)
                && (jToggleButtonCartaoCredito.isSelected() == true
                || (jToggleButton_Pix.isSelected() == true))) {
            if(jToggleButtonCartaoCredito.isSelected() == true
                &&(jLabel_Obrigatorio4.isVisible()== false)
                && (jLabel_Obrigatorio5.isVisible() == false) 
                && (jLabel_Obrigatorio7.isVisible() == false)){
                JOptionPane.showMessageDialog(null, "DADOS VALIDADOS!!");
                flag = JOptionPane.showConfirmDialog(null, "DADOS INFORMADOS ESTÃO CORRETOS?", "Confirmar seleção!", NORMAL);
            }else{
                JOptionPane.showMessageDialog(null, "CONFIRA OS CAMPOS OBRIGATÓRIOS OU ACEITE OS TERMOS DE USO!!");
            }
            if(jToggleButton_Pix.isSelected() == true){
                JOptionPane.showMessageDialog(null, "DADOS VALIDADOS!!");
                flag = JOptionPane.showConfirmDialog(null, "DADOS INFORMADOS ESTÃO CORRETOS?", "Confirmar seleção!", NORMAL);
            }else{
                //JOptionPane.showMessageDialog(null, "CONFIRA OS CAMPOS OBRIGATÓRIOS OU ACEITE OS TERMOS DE USO!!");
            }
            if(flag == 0){//0 == sim
                //frmMenuInformacoesP infP = new frmMenuInformacoesP();
                //infP.setVisible(true);
                int flag2 = 0;
                flag2 = JOptionPane.showConfirmDialog(null, "Nome: "+jTextField_Nome.getText() + "\nE-mail: "+jTextField_Email.getText() +"\nCPF: "+jTextField_Cpf.getText() +
                        "\n Telefone: "+jTextField_Telefone.getText() + "\n"+ jTextField_Empresa.getText() + "\n"+ jTextField_Origem.getText()+"/"+jTextField_Destino.getText()+
                        "\n"+ jTextField_Tipo.getText() + "\n"+ jTextField_Horario.getText() + "\nTarifa: "+jTextField_Tarifa.getText(), "CONFIRMAR INFOMAÇÕES!", NORMAL);
                if(flag2 == 0){
                    //frmMenuVendasCadastradas cadastrada = new frmMenuVendasCadastradas();
                    //cadastrada.setVisible(true);
                    enviarInf = new frmMenuVendasCadastradas();
                    enviarInf.receberCliente(jTextField_Nome.getText());
                    enviarInf.receberEmpresa(jTextField_Empresa.getText());
                    enviarInf.receberRota(jTextField_Origem.getText(), jTextField_Destino.getText());
                    enviarInf.receberTarifa(jTextField_Tarifa.getText());
                    enviarInf.setVisible(true);
                }else{
                    jTextField_Nome.requestFocus();
                }
            }

            if(flag == 1){//1 == não
                jTextField_Nome.requestFocus();
            }else{
                //JOptionPane.showMessageDialog(rootPane, "ASSENTO NÃO SELECIONADO!");
                //jToggleButton1.requestFocus();
        }  
        } else {
            JOptionPane.showMessageDialog(null, "CONFIRA OS CAMPOS OBRIGATÓRIOS OU ACEITE OS TERMOS DE USO!!");
        }
    }//GEN-LAST:event_jButton_FinalizarCompraActionPerformed

    private void jTextField_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NomeActionPerformed

    private void jLabel_Obrigatorio4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_Obrigatorio4PropertyChange
        // TODO add your handling code here:
        jLabel_Obrigatorio4.setVisible(false);
    }//GEN-LAST:event_jLabel_Obrigatorio4PropertyChange

    private void jLabel_Obrigatorio5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_Obrigatorio5PropertyChange
        // TODO add your handling code here:
        jLabel_Obrigatorio5.setVisible(false);
    }//GEN-LAST:event_jLabel_Obrigatorio5PropertyChange

    private void jLabel_Obrigatorio7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_Obrigatorio7PropertyChange
        // TODO add your handling code here:
        jLabel_Obrigatorio7.setVisible(false);
    }//GEN-LAST:event_jLabel_Obrigatorio7PropertyChange

    private void jToggleButtonCartaoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCartaoCreditoActionPerformed
        // TODO add your handling code here:
        if(jToggleButtonCartaoCredito.isSelected() == true){
            jLabel_Obrigatorio4.setVisible(true);
            jLabel_Obrigatorio5.setVisible(true);
            jLabel_Obrigatorio7.setVisible(true);
            
            jTextField_NomeTitular.setEnabled(true);
            jTextField_CEP.setEnabled(true);
            jTextField_NCartao.setEnabled(true);
            jTextField_Cpf1.setEnabled(true);
            jTextField_CodSeguranca.setEnabled(true);
            jTextField_DataValidade.setEnabled(true);
            jTextField_DataValidade.setText("");
            
            jComboBox_Parcelas.setEnabled(true);
            
            jButton_Validar.setEnabled(true);
            
        }else{
            jLabel_Obrigatorio4.setVisible(false);
            jLabel_Obrigatorio5.setVisible(false);
            jLabel_Obrigatorio7.setVisible(false);
            
            jTextField_NomeTitular.setEnabled(false);
            jTextField_CEP.setEnabled(false);
            jTextField_NCartao.setEnabled(false);
            jTextField_Cpf1.setEnabled(false);
            jTextField_CodSeguranca.setEnabled(false);
            jTextField_DataValidade.setEnabled(false);
            jTextField_DataValidade.setText("mm/aa");
            
            jComboBox_Parcelas.setEnabled(false);
            
            jButton_Validar.setEnabled(false);
        }
    }//GEN-LAST:event_jToggleButtonCartaoCreditoActionPerformed

    private void jButton_ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ValidarActionPerformed
        // TODO add your handling code here:
        if (jTextField_NomeTitular.getText().length() > 0) {
            jLabel_Obrigatorio4.setVisible(false);
        } else {
            jLabel_Obrigatorio4.setVisible(true);
        }

        if (jTextField_CEP.getText().length() > 0) {
            jLabel_Obrigatorio4.setVisible(false);
        } else {
            jLabel_Obrigatorio4.setVisible(true);
        }
        if (jTextField_NCartao.getText().length() > 0) {
            jLabel_Obrigatorio5.setVisible(false);
        } else {
            jLabel_Obrigatorio5.setVisible(true);
        }
        if (jTextField_Cpf1.getText().length() > 0) {
            jLabel_Obrigatorio5.setVisible(false);
        } else {
            jLabel_Obrigatorio5.setVisible(true);
        }
        if (jTextField_CodSeguranca.getText().length() > 0) {
            jLabel_Obrigatorio7.setVisible(false);
        } else {
            jLabel_Obrigatorio7.setVisible(true);
        }
        /*if (jTextField_DataValidade.getText().length() > 0) {
            jLabel_Obrigatorio7.setVisible(false);
        } else {
            jLabel_Obrigatorio7.setVisible(true);
        }*/
        if ((jTextField_NomeTitular.getText().length()>0)
                &&(jTextField_CEP.getText().length()> 0)
                && (jTextField_NCartao.getText().length() > 0) 
                && (jTextField_Cpf1.getText().length() > 0)
                && (jTextField_CodSeguranca.getText().length() > 0)
                && (jTextField_DataValidade.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "DADOS VALIDADOS!!");
            jTextField_NomeTitular.setEnabled(false);
            jTextField_CEP.setEnabled(false);
            jTextField_NCartao.setEnabled(false);
            jTextField_Cpf1.setEnabled(false);
            jTextField_CodSeguranca.setEnabled(false);
            jTextField_DataValidade.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "CONFIRA OS CAMPOS OBRIGATÓRIOS!!");
        }
    }//GEN-LAST:event_jButton_ValidarActionPerformed

    private void jToggleButton_PixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_PixActionPerformed
        // TODO add your handling code here:
        if(jToggleButton_Pix.isSelected() == true){
            /*jLabel_Obrigatorio4.setVisible(true);
            jLabel_Obrigatorio5.setVisible(true);
            jLabel_Obrigatorio7.setVisible(true);*/
            
            jTextField_NomeTitular.setEnabled(false);
            jTextField_CEP.setEnabled(false);
            jTextField_NCartao.setEnabled(false);
            jTextField_Cpf1.setEnabled(false);
            jTextField_CodSeguranca.setEnabled(false);
            jTextField_DataValidade.setEnabled(false);
            jTextField_DataValidade.setText("mm/aa");
            
            jComboBox_Parcelas.setEnabled(false);
            
            jButton_Validar.setEnabled(false);
            
            jToggleButtonCartaoCredito.setSelected(false);
            
            jLabel_Qrcode.setVisible(true);
            JOptionPane.showMessageDialog(null, "USE O SEU CELULAR PARA SCANEAR O QRCODE!!");
        }else{
            jToggleButton_Pix.setSelected(false);
            jLabel_Qrcode.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButton_PixActionPerformed

    private void jLabel_QrcodePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_QrcodePropertyChange
        // TODO add your handling code here:
        jLabel_Qrcode.setVisible(false);
    }//GEN-LAST:event_jLabel_QrcodePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuInformacoesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuInformacoesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuInformacoesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuInformacoesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuInformacoesP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_FinalizarCompra;
    private javax.swing.JButton jButton_Validar;
    private javax.swing.JCheckBox jCheckBox_TermoDeUso;
    private javax.swing.JComboBox<String> jComboBox_Parcelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_CEP;
    private javax.swing.JLabel jLabel_CodSeguranca;
    private javax.swing.JLabel jLabel_Comprador;
    private javax.swing.JLabel jLabel_Comprador1;
    private javax.swing.JLabel jLabel_Confirmacao_e_Dados;
    private javax.swing.JLabel jLabel_Cpf;
    private javax.swing.JLabel jLabel_Cpf1;
    private javax.swing.JLabel jLabel_DataValidade;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_NCartao;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_NomeTitular;
    private javax.swing.JLabel jLabel_Obrigatorio;
    private javax.swing.JLabel jLabel_Obrigatorio1;
    private javax.swing.JLabel jLabel_Obrigatorio2;
    private javax.swing.JLabel jLabel_Obrigatorio3;
    private javax.swing.JLabel jLabel_Obrigatorio4;
    private javax.swing.JLabel jLabel_Obrigatorio5;
    private javax.swing.JLabel jLabel_Obrigatorio7;
    private javax.swing.JLabel jLabel_Parcelas;
    private javax.swing.JLabel jLabel_Qrcode;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JPanel jPanel_Cartao;
    private javax.swing.JPanel jPanel_Pix;
    private javax.swing.JPanel jPanel_QRCode;
    private javax.swing.JTextField jTextField_CEP;
    private javax.swing.JTextField jTextField_CodSeguranca;
    private javax.swing.JTextField jTextField_Cpf;
    private javax.swing.JTextField jTextField_Cpf1;
    private javax.swing.JTextField jTextField_DataValidade;
    private javax.swing.JTextField jTextField_Destino;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Empresa;
    private javax.swing.JTextField jTextField_Horario;
    private javax.swing.JTextField jTextField_NCartao;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JTextField jTextField_NomeTitular;
    private javax.swing.JTextField jTextField_Origem;
    private javax.swing.JTextField jTextField_Tarifa;
    private javax.swing.JTextField jTextField_Telefone;
    private javax.swing.JTextField jTextField_Tipo;
    private javax.swing.JToggleButton jToggleButtonCartaoCredito;
    private javax.swing.JToggleButton jToggleButton_Pix;
    // End of variables declaration//GEN-END:variables
    public void receberEmpresa(String empresa){
        jTextField_Empresa.setText(empresa);
    }
    
    public void receberRota(String origem, String destino){
        jTextField_Origem.setText(origem);
        jTextField_Destino.setText(destino);
    }
    
    public void receberTipo(String tipo){
        jTextField_Tipo.setText(tipo);
    }
    
    public void receberHorario(String horario){
        jTextField_Horario.setText(horario);
    }
    
    public void receberTarifa(String tarifa){
        jTextField_Tarifa.setText(tarifa);
    }
}
