/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class frmMenuSelecaoViagem01 extends javax.swing.JFrame {

    frmMenuAssentos01_Rota_01 enviaTexto;
    frmMenuAssentos01_Rota_02 enviaTexto2;
    frmMenuAssentos01_Rota_03 enviaTexto3;
    
    frmMenuAssentos01_Rota_01 enviaPreco;
    frmMenuAssentos01_Rota_02 enviaPreco2;
    frmMenuAssentos01_Rota_03 enviaPreco3;
    
    frmMenuAssentos01_Rota_01 enviaInf;
    frmMenuAssentos01_Rota_02 enviaInf2;
    frmMenuAssentos01_Rota_03 enviaInf3;
    
    public double preco;
    /**
     * Creates new form frmMenuSelecaoViagem
     */
    public frmMenuSelecaoViagem01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton_SelecionarViagem3 = new javax.swing.JButton();
        jButton_SelecionarViagem2 = new javax.swing.JButton();
        jButton_SelecionarViagem1 = new javax.swing.JButton();
        jLabel_Empresa = new javax.swing.JLabel();
        jLabel_Trecho = new javax.swing.JLabel();
        jLabel_Horario = new javax.swing.JLabel();
        jLabel_Tarifa = new javax.swing.JLabel();
        jLabel_EmpresaMuffin = new javax.swing.JLabel();
        jLabel_TrechoSaoLuis = new javax.swing.JLabel();
        jLabel_TrechoBacabal = new javax.swing.JLabel();
        jLabel_ClasseCovencional = new javax.swing.JLabel();
        jButton_ConvencionalI = new javax.swing.JButton();
        jLabel_Horario0800 = new javax.swing.JLabel();
        jLabel_Horario1 = new javax.swing.JLabel();
        jLabel_Tarifa1 = new javax.swing.JLabel();
        jLabel_TrechoSaoLuis1 = new javax.swing.JLabel();
        jLabel_TrechoBacabal1 = new javax.swing.JLabel();
        jLabel_ClasseLeito = new javax.swing.JLabel();
        jButton_LeitoI = new javax.swing.JButton();
        jLabel_Horario1320 = new javax.swing.JLabel();
        jLabel_Trecho1 = new javax.swing.JLabel();
        jLabel_EmpresaMuffin1 = new javax.swing.JLabel();
        jLabel_Empresa1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_TrechoSaoLuis2 = new javax.swing.JLabel();
        jLabel_TrechoBacabal2 = new javax.swing.JLabel();
        jLabel_ClasseExecutivo = new javax.swing.JLabel();
        jButton_ExecutivoI = new javax.swing.JButton();
        jLabel_Horario1700 = new javax.swing.JLabel();
        jLabel_Trecho2 = new javax.swing.JLabel();
        jLabel_EmpresaMuffin2 = new javax.swing.JLabel();
        jLabel_Empresa2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_Horario2 = new javax.swing.JLabel();
        jLabel_Tarifa2 = new javax.swing.JLabel();
        jRadioButton_Ida = new javax.swing.JRadioButton();
        jRadioButton_IdaVolta = new javax.swing.JRadioButton();
        jRadioButton_Ida1 = new javax.swing.JRadioButton();
        jRadioButton_IdaVolta1 = new javax.swing.JRadioButton();
        jRadioButton_Ida2 = new javax.swing.JRadioButton();
        jRadioButton_IdaVolta2 = new javax.swing.JRadioButton();
        jButton_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_SelecionarViagem3.setText("Selecionar");
        jButton_SelecionarViagem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarViagem3ActionPerformed(evt);
            }
        });

        jButton_SelecionarViagem2.setText("Selecionar");
        jButton_SelecionarViagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarViagem2ActionPerformed(evt);
            }
        });

        jButton_SelecionarViagem1.setText("Selecionar");
        jButton_SelecionarViagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarViagem1ActionPerformed(evt);
            }
        });

        jLabel_Empresa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Empresa.setText("EMPRERSA");

        jLabel_Trecho.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Trecho.setText("TRECHO/CLASSE");

        jLabel_Horario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Horario.setText("HORÁRIO/DURAÇÃO");

        jLabel_Tarifa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Tarifa.setText("TARIFA");

        jLabel_EmpresaMuffin.setFont(new java.awt.Font("Futura CondensedLight", 3, 24)); // NOI18N
        jLabel_EmpresaMuffin.setText("MUFFIN");

        jLabel_TrechoSaoLuis.setText("SAO LUIS (MA)");

        jLabel_TrechoBacabal.setText("BACABAL (MA)");

        jLabel_ClasseCovencional.setText("CONVENCIONAL");

        jButton_ConvencionalI.setText("i");
        jButton_ConvencionalI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConvencionalIActionPerformed(evt);
            }
        });

        jLabel_Horario0800.setText("08:00 - 12:50");

        jLabel_Horario1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Horario1.setText("HORÁRIO/DURAÇÃO");

        jLabel_Tarifa1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Tarifa1.setText("TARIFA");

        jLabel_TrechoSaoLuis1.setText("SAO LUIS (MA)");

        jLabel_TrechoBacabal1.setText("BACABAL (MA)");

        jLabel_ClasseLeito.setText("LEITO");

        jButton_LeitoI.setText("i");
        jButton_LeitoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LeitoIActionPerformed(evt);
            }
        });

        jLabel_Horario1320.setText("13:20 - 18:23");

        jLabel_Trecho1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Trecho1.setText("TRECHO/CLASSE");

        jLabel_EmpresaMuffin1.setFont(new java.awt.Font("Futura CondensedLight", 3, 24)); // NOI18N
        jLabel_EmpresaMuffin1.setText("MUFFIN");

        jLabel_Empresa1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Empresa1.setText("EMPRERSA");

        jLabel_TrechoSaoLuis2.setText("SAO LUIS (MA)");

        jLabel_TrechoBacabal2.setText("BACABAL (MA)");

        jLabel_ClasseExecutivo.setText("EXECUTIVO");

        jButton_ExecutivoI.setText("i");
        jButton_ExecutivoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExecutivoIActionPerformed(evt);
            }
        });

        jLabel_Horario1700.setText("17:00 - 21:28");

        jLabel_Trecho2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Trecho2.setText("TRECHO/CLASSE");

        jLabel_EmpresaMuffin2.setFont(new java.awt.Font("Futura CondensedLight", 3, 24)); // NOI18N
        jLabel_EmpresaMuffin2.setText("MUFFIN");

        jLabel_Empresa2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Empresa2.setText("EMPRERSA");

        jLabel_Horario2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Horario2.setText("HORÁRIO/DURAÇÃO");

        jLabel_Tarifa2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Tarifa2.setText("TARIFA");

        buttonGroup1.add(jRadioButton_Ida);
        jRadioButton_Ida.setText("IDA: R$ 61,73");
        jRadioButton_Ida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_IdaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_IdaVolta);
        jRadioButton_IdaVolta.setText("IDA E VOLTA: R$ 123,46");

        buttonGroup2.add(jRadioButton_Ida1);
        jRadioButton_Ida1.setText("IDA: R$ 90,90");

        buttonGroup2.add(jRadioButton_IdaVolta1);
        jRadioButton_IdaVolta1.setText("IDA E VOLTA: R$ 181,80");

        buttonGroup3.add(jRadioButton_Ida2);
        jRadioButton_Ida2.setText("IDA: R$ 66,40");

        buttonGroup3.add(jRadioButton_IdaVolta2);
        jRadioButton_IdaVolta2.setText("IDA E VOLTA: R$ 132,80");

        jButton_Voltar.setText("Voltar");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_EmpresaMuffin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_EmpresaMuffin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Empresa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_TrechoSaoLuis1)
                                            .addComponent(jLabel_TrechoBacabal1))
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel_ClasseLeito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_LeitoI)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jRadioButton_Ida)
                                                        .addGap(70, 70, 70))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jRadioButton_IdaVolta)
                                                        .addGap(31, 31, 31)))
                                                .addComponent(jButton_SelecionarViagem1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jRadioButton_Ida1)
                                                .addGap(73, 73, 73)
                                                .addComponent(jButton_SelecionarViagem2)))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_TrechoBacabal)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel_TrechoSaoLuis)
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel_ClasseCovencional)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_ConvencionalI)
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel_Horario0800)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_Trecho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Horario)
                                .addGap(113, 113, 113)
                                .addComponent(jLabel_Tarifa)
                                .addGap(193, 193, 193))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Trecho1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(210, 210, 210)
                                        .addComponent(jLabel_Horario1320)
                                        .addGap(76, 76, 76)
                                        .addComponent(jRadioButton_IdaVolta1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(jLabel_Horario1)
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel_Tarifa1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_EmpresaMuffin2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Empresa2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_TrechoSaoLuis2)
                                    .addComponent(jLabel_TrechoBacabal2))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel_ClasseExecutivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ExecutivoI))
                            .addComponent(jLabel_Trecho2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel_Horario2)
                                .addGap(119, 119, 119)
                                .addComponent(jLabel_Tarifa2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel_Horario1700)
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Ida2)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jRadioButton_IdaVolta2)
                                        .addGap(41, 41, 41)))
                                .addComponent(jButton_SelecionarViagem3)
                                .addGap(22, 22, 22))))
                    .addComponent(jSeparator2)))
            .addGroup(layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jButton_Voltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Empresa)
                        .addComponent(jLabel_Trecho))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Tarifa)
                        .addComponent(jLabel_Horario)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_ClasseCovencional)
                                        .addComponent(jButton_ConvencionalI)
                                        .addComponent(jLabel_Horario0800))
                                    .addComponent(jLabel_TrechoSaoLuis))
                                .addGap(4, 4, 4)
                                .addComponent(jLabel_TrechoBacabal)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel_EmpresaMuffin))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_Ida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_IdaVolta)))
                                .addGap(40, 40, 40)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton_SelecionarViagem1)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Horario1)
                    .addComponent(jLabel_Tarifa1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Empresa1)
                        .addComponent(jLabel_Trecho1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_SelecionarViagem2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_ClasseLeito)
                                    .addComponent(jButton_LeitoI)
                                    .addComponent(jLabel_Horario1320))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_TrechoSaoLuis1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel_TrechoBacabal1)))
                            .addComponent(jLabel_EmpresaMuffin1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Ida1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_IdaVolta1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Empresa2)
                        .addComponent(jLabel_Trecho2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_Horario2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_Tarifa2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_EmpresaMuffin2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_ClasseExecutivo)
                                .addComponent(jButton_ExecutivoI)
                                .addComponent(jLabel_Horario1700))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_TrechoSaoLuis2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_TrechoBacabal2))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Ida2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_IdaVolta2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton_SelecionarViagem3)))
                .addGap(22, 22, 22)
                .addComponent(jButton_Voltar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // TODO add your handling code here:
        frmMenuSelecaoViagem01 viagem01 = new frmMenuSelecaoViagem01();
        dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    private void jButton_ConvencionalIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConvencionalIActionPerformed
        // TODO add your handling code here:
        frmMenuConvencional convencional = new frmMenuConvencional();
        convencional.setVisible(true);
    }//GEN-LAST:event_jButton_ConvencionalIActionPerformed

    private void jButton_LeitoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LeitoIActionPerformed
        // TODO add your handling code here:
        frmMenuLeito leito = new frmMenuLeito();
        leito.setVisible(true);
    }//GEN-LAST:event_jButton_LeitoIActionPerformed

    private void jButton_ExecutivoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExecutivoIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ExecutivoIActionPerformed

    private void jButton_SelecionarViagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarViagem1ActionPerformed
        // TODO add your handling code here:
        String buttonText1 = new String();
        enviaInf = new frmMenuAssentos01_Rota_01();
        enviaPreco = new frmMenuAssentos01_Rota_01();
        enviaTexto = new frmMenuAssentos01_Rota_01();
        if(jRadioButton_Ida.isSelected() == true){
            buttonText1 = jRadioButton_Ida.getText();
            enviaTexto.recebendoV1(jRadioButton_Ida.getText());
            preco = 61.73;
            enviaPreco.recebendoPreco1(preco);
            enviaInf.receberEmpresa(jLabel_EmpresaMuffin.getText());
            enviaInf.receberRota(jLabel_TrechoSaoLuis.getText(), jLabel_TrechoBacabal.getText());
            enviaInf.receberTipo(jLabel_ClasseCovencional.getText());
            enviaInf.receberHorario(jLabel_Horario0800.getText());
            enviaInf.receberTarifa(jRadioButton_Ida.getText());
        }else if(jRadioButton_IdaVolta.isSelected() == true){
            buttonText1 = jRadioButton_IdaVolta.getText();
            enviaTexto.recebendoV1(jRadioButton_IdaVolta.getText());
            preco = 123.46;
            enviaPreco.recebendoPreco1(preco);
            enviaInf.receberEmpresa(jLabel_EmpresaMuffin.getText());
            enviaInf.receberRota(jLabel_TrechoSaoLuis.getText(), jLabel_TrechoBacabal.getText());
            enviaInf.receberTipo(jLabel_ClasseCovencional.getText());
            enviaInf.receberHorario(jLabel_Horario0800.getText());
            enviaInf.receberTarifa(jRadioButton_IdaVolta.getText());
        }
        int flag = JOptionPane.showConfirmDialog(null, "Empresa: "+jLabel_EmpresaMuffin.getText()+
                "\nTrecho/Classe: "+jLabel_TrechoSaoLuis.getText()+" -> "+jLabel_TrechoBacabal.getText()+" / "+jLabel_ClasseCovencional.getText()+
                "\nHorário/Duração: "+jLabel_Horario0800.getText()+
                "\nTarifa: "+ buttonText1,"Confirmar seleção!", NORMAL);
        if(jRadioButton_Ida.isSelected() == true || jRadioButton_IdaVolta.isSelected() == true){
            if(flag == 0){//0 == sim
                frmMenuAssentos01_Rota_01 assentos01 = new frmMenuAssentos01_Rota_01();
                //assentos01.setVisible(true);
                //enviaTexto.setVisible(true);
                enviaInf.setVisible(true);
            }

            if(flag == 1){//1 == não
                jButton_SelecionarViagem1.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "TARIFA NÃO SELECIONADA!");
            jRadioButton_Ida.requestFocus();
        }    
    }//GEN-LAST:event_jButton_SelecionarViagem1ActionPerformed

    private void jRadioButton_IdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_IdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_IdaActionPerformed

    private void jButton_SelecionarViagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarViagem2ActionPerformed
        // TODO add your handling code here:
        String buttonText2 = new String();
        enviaInf2 = new frmMenuAssentos01_Rota_02();
        enviaPreco2 = new frmMenuAssentos01_Rota_02();
        enviaTexto2 = new frmMenuAssentos01_Rota_02();
        if(jRadioButton_Ida1.isSelected() == true){
            buttonText2 = jRadioButton_Ida1.getText();
            enviaTexto2.recebendoV2(jRadioButton_Ida1.getText());
            preco = 90.90;
            enviaPreco2.recebendoPreco2(preco);
            enviaInf2.receberEmpresa(jLabel_EmpresaMuffin1.getText());
            enviaInf2.receberRota(jLabel_TrechoSaoLuis1.getText(), jLabel_TrechoBacabal1.getText());
            enviaInf2.receberTipo(jLabel_ClasseLeito.getText());
            enviaInf2.receberHorario(jLabel_Horario1320.getText());
            enviaInf2.receberTarifa(jRadioButton_Ida1.getText());
        }else if(jRadioButton_IdaVolta1.isSelected() == true){
            buttonText2 = jRadioButton_IdaVolta1.getText();
            enviaTexto2.recebendoV2(jRadioButton_Ida1.getText());
            preco = 181.80;
            enviaPreco2.recebendoPreco2(preco);
            enviaInf2.receberEmpresa(jLabel_EmpresaMuffin1.getText());
            enviaInf2.receberRota(jLabel_TrechoSaoLuis1.getText(), jLabel_TrechoBacabal1.getText());
            enviaInf2.receberTipo(jLabel_ClasseLeito.getText());
            enviaInf2.receberHorario(jLabel_Horario1320.getText());
            enviaInf2.receberTarifa(jRadioButton_IdaVolta1.getText());
        }
        int flag = JOptionPane.showConfirmDialog(null, "Empresa: "+jLabel_EmpresaMuffin1.getText()+
                "\nTrecho/Classe: "+jLabel_TrechoSaoLuis1.getText()+" -> "+jLabel_TrechoBacabal1.getText()+" / "+jLabel_ClasseLeito.getText()+
                "\nHorário/Duração: "+jLabel_Horario1320.getText()+
                "\nTarifa: "+ buttonText2,"Confirmar seleção!", NORMAL);
        if(jRadioButton_Ida1.isSelected() == true || jRadioButton_IdaVolta1.isSelected() == true){
            if(flag == 0){//0 == sim
                frmMenuAssentos02_Rora_01 assentos02 = new frmMenuAssentos02_Rora_01();
                //assentos02.setVisible(true);
                //enviaTexto2.setVisible(true);
                enviaInf2.setVisible(true);
            }

            if(flag == 1){//1 == não
                jButton_SelecionarViagem2.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "TARIFA NÃO SELECIONADA!");
            jRadioButton_Ida1.requestFocus();
        }
    }//GEN-LAST:event_jButton_SelecionarViagem2ActionPerformed

    private void jButton_SelecionarViagem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarViagem3ActionPerformed
        // TODO add your handling code here:
        String buttonText3 = new String();
        enviaInf3 = new frmMenuAssentos01_Rota_03();
        enviaPreco3 = new frmMenuAssentos01_Rota_03();
        enviaTexto3 = new frmMenuAssentos01_Rota_03();
        if(jRadioButton_Ida2.isSelected() == true){
            buttonText3 = jRadioButton_Ida2.getText();
            enviaTexto3.recebendoV3(jRadioButton_Ida2.getText());
            preco = 66.40;
            enviaPreco3.recebendoPreco3(preco);
            enviaInf3.receberEmpresa(jLabel_EmpresaMuffin2.getText());
            enviaInf3.receberRota(jLabel_TrechoSaoLuis2.getText(), jLabel_TrechoBacabal2.getText());
            enviaInf3.receberTipo(jLabel_ClasseExecutivo.getText());
            enviaInf3.receberHorario(jLabel_Horario1700.getText());
            enviaInf3.receberTarifa(jRadioButton_Ida2.getText());
        }else if(jRadioButton_IdaVolta2.isSelected() == true){
            buttonText3 = jRadioButton_IdaVolta2.getText();
            enviaTexto3.recebendoV3(jRadioButton_IdaVolta2.getText());
            preco = 132.80;
            enviaPreco3.recebendoPreco3(preco);
            enviaInf3.receberEmpresa(jLabel_EmpresaMuffin2.getText());
            enviaInf3.receberRota(jLabel_TrechoSaoLuis2.getText(), jLabel_TrechoBacabal2.getText());
            enviaInf3.receberTipo(jLabel_ClasseExecutivo.getText());
            enviaInf3.receberHorario(jLabel_Horario1700.getText());
            enviaInf3.receberTarifa(jRadioButton_IdaVolta2.getText());
        }
        int flag = JOptionPane.showConfirmDialog(null, "Empresa: "+jLabel_EmpresaMuffin2.getText()+
                "\nTrecho/Classe: "+jLabel_TrechoSaoLuis2.getText()+" -> "+jLabel_TrechoBacabal2.getText()+" / "+jLabel_ClasseExecutivo.getText()+
                "\nHorário/Duração: "+jLabel_Horario1700.getText()+
                "\nTarifa: "+ buttonText3,"Confirmar seleção!", NORMAL);
        
        if(jRadioButton_Ida2.isSelected() == true || jRadioButton_IdaVolta2.isSelected() == true){
            if(flag == 0){//0 == sim
                frmMenuAssentos03_Rota_01 assentos03 = new frmMenuAssentos03_Rota_01();
                //assentos03.setVisible(true);
                //enviaTexto3.setVisible(true);
                enviaInf3.setVisible(true);
            }

            if(flag == 1){//1 == não
                jButton_SelecionarViagem3.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "TARIFA NÃO SELECIONADA!");
            jRadioButton_Ida2.requestFocus();
        }
    }//GEN-LAST:event_jButton_SelecionarViagem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuSelecaoViagem01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton_ConvencionalI;
    private javax.swing.JButton jButton_ExecutivoI;
    private javax.swing.JButton jButton_LeitoI;
    private javax.swing.JButton jButton_SelecionarViagem1;
    private javax.swing.JButton jButton_SelecionarViagem2;
    private javax.swing.JButton jButton_SelecionarViagem3;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel_ClasseCovencional;
    private javax.swing.JLabel jLabel_ClasseExecutivo;
    private javax.swing.JLabel jLabel_ClasseLeito;
    private javax.swing.JLabel jLabel_Empresa;
    private javax.swing.JLabel jLabel_Empresa1;
    private javax.swing.JLabel jLabel_Empresa2;
    private javax.swing.JLabel jLabel_EmpresaMuffin;
    private javax.swing.JLabel jLabel_EmpresaMuffin1;
    private javax.swing.JLabel jLabel_EmpresaMuffin2;
    private javax.swing.JLabel jLabel_Horario;
    private javax.swing.JLabel jLabel_Horario0800;
    private javax.swing.JLabel jLabel_Horario1;
    private javax.swing.JLabel jLabel_Horario1320;
    private javax.swing.JLabel jLabel_Horario1700;
    private javax.swing.JLabel jLabel_Horario2;
    private javax.swing.JLabel jLabel_Tarifa;
    private javax.swing.JLabel jLabel_Tarifa1;
    private javax.swing.JLabel jLabel_Tarifa2;
    private javax.swing.JLabel jLabel_Trecho;
    private javax.swing.JLabel jLabel_Trecho1;
    private javax.swing.JLabel jLabel_Trecho2;
    private javax.swing.JLabel jLabel_TrechoBacabal;
    private javax.swing.JLabel jLabel_TrechoBacabal1;
    private javax.swing.JLabel jLabel_TrechoBacabal2;
    private javax.swing.JLabel jLabel_TrechoSaoLuis;
    private javax.swing.JLabel jLabel_TrechoSaoLuis1;
    private javax.swing.JLabel jLabel_TrechoSaoLuis2;
    private javax.swing.JRadioButton jRadioButton_Ida;
    private javax.swing.JRadioButton jRadioButton_Ida1;
    private javax.swing.JRadioButton jRadioButton_Ida2;
    private javax.swing.JRadioButton jRadioButton_IdaVolta;
    private javax.swing.JRadioButton jRadioButton_IdaVolta1;
    private javax.swing.JRadioButton jRadioButton_IdaVolta2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
