/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

import classes.Usuario;
import static java.awt.Frame.NORMAL;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class frmMenuInfViagem extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuInfViagem
     */
    public frmMenuInfViagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Origem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Destino = new javax.swing.JLabel();
        jTextField_Origem = new javax.swing.JTextField();
        jTextField_Destino = new javax.swing.JTextField();
        jLabel_DataIda = new javax.swing.JLabel();
        jComboBox_Dia = new javax.swing.JComboBox<>();
        jLabel_Dia = new javax.swing.JLabel();
        jLabel_Mes = new javax.swing.JLabel();
        jComboBox_Mes = new javax.swing.JComboBox<>();
        jLabel_Ano = new javax.swing.JLabel();
        jComboBox_Ano = new javax.swing.JComboBox<>();
        jLabel_CupomD = new javax.swing.JLabel();
        jTextField_CupomD = new javax.swing.JTextField();
        jToggleButton_Buscar = new javax.swing.JToggleButton();
        jLabel_Dia1 = new javax.swing.JLabel();
        jLabel_Mes1 = new javax.swing.JLabel();
        jComboBox_Mes1 = new javax.swing.JComboBox<>();
        jLabel_Ano1 = new javax.swing.JLabel();
        jComboBox_Ano1 = new javax.swing.JComboBox<>();
        jLabel_DataVolta = new javax.swing.JLabel();
        jComboBox_Dia1 = new javax.swing.JComboBox<>();
        jButton_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Origem.setText("Origem:");

        jLabel1.setFont(new java.awt.Font("Futura CondensedLight", 3, 24)); // NOI18N
        jLabel1.setText("Informações da Viagem");

        jLabel_Destino.setText("Destino:");

        jTextField_Origem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_OrigemActionPerformed(evt);
            }
        });

        jTextField_Destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DestinoActionPerformed(evt);
            }
        });

        jLabel_DataIda.setText("Data de ida:");

        jComboBox_Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel_Dia.setText("Dia:");

        jLabel_Mes.setText("Mês:");

        jComboBox_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel_Ano.setText("Dia:");

        jComboBox_Ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022" }));

        jLabel_CupomD.setText("Cubom de Desconto:");

        jTextField_CupomD.setText("INDISPONÍVEL");
        jTextField_CupomD.setToolTipText("");
        jTextField_CupomD.setEnabled(false);
        jTextField_CupomD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CupomDActionPerformed(evt);
            }
        });

        jToggleButton_Buscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jToggleButton_Buscar.setText("Buscar");
        jToggleButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_BuscarActionPerformed(evt);
            }
        });

        jLabel_Dia1.setText("Dia:");

        jLabel_Mes1.setText("Mês:");

        jComboBox_Mes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel_Ano1.setText("Dia:");

        jComboBox_Ano1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022" }));

        jLabel_DataVolta.setText("Data de volta:");

        jComboBox_Dia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jButton_Voltar.setText("VOLTAR");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Destino)
                            .addComponent(jLabel_Origem))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Origem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_CupomD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CupomD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_DataIda)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel_Dia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel_Mes)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel_Ano))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_DataVolta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel_Dia1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_Dia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_Mes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel_Mes1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_Ano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel_Ano1)))))
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Voltar)
                        .addGap(66, 66, 66)
                        .addComponent(jToggleButton_Buscar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Origem)
                    .addComponent(jTextField_Origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Destino)
                    .addComponent(jTextField_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Mes)
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DataIda)
                            .addComponent(jLabel_Dia))
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Ano)
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Mes1)
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox_Mes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DataVolta)
                            .addComponent(jLabel_Dia1))
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox_Dia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Ano1)
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox_Ano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CupomD)
                    .addComponent(jTextField_CupomD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_Buscar)
                    .addComponent(jButton_Voltar))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DestinoActionPerformed

    private void jTextField_CupomDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CupomDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CupomDActionPerformed

    private void jToggleButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_BuscarActionPerformed
        // TODO add your handling code here:
        frmMenuSelecaoViagem01 viagem01 = new frmMenuSelecaoViagem01();
        frmMenuSelecaoViagem02 viagem02 = new frmMenuSelecaoViagem02();
        frmMenuSelecaoViagem03 viagem03 = new frmMenuSelecaoViagem03();
        Usuario user = new Usuario();
        int flag = JOptionPane.showConfirmDialog(null, "Origem: "+jTextField_Origem.getText()+
                "\nDestino: "+jTextField_Destino.getText()+
                "\nData de ida: "+jComboBox_Dia.getSelectedItem()+
                "/"+ jComboBox_Mes.getSelectedItem() + "/" + jComboBox_Ano.getSelectedItem()+
                "\nData de volta: "+jComboBox_Dia1.getSelectedItem()+
                "/"+ jComboBox_Mes1.getSelectedItem() + "/" + jComboBox_Ano1.getSelectedItem()+
                "\nCupom de desconto: "+jTextField_CupomD.getText() ,"Confirmar informações!", NORMAL);
        
        if(flag == 0){//0 == sim
            /*JOptionPane.showMessageDialog(null, "Dados preenchidos", "Gui Swing", JOptionPane.PLAIN_MESSAGE);
            jTextField_Origem.setText("");
            jTextField_Destino.setText("");
            jTextField_Origem.requestFocus();*/
            if (user.validarViagem(jTextField_Origem.getText(), jTextField_Destino.getText()) == 0) {
            JOptionPane.showMessageDialog(rootPane, "VIAGEM NÃO ENCONTRADA!\nTENTE ALTERAR A ORIGEM OU DESTINO.");
            jTextField_Origem.setText("");
            jTextField_Destino.setText("");
            jTextField_Origem.requestFocus();
            }
            if(user.validarViagem(jTextField_Origem.getText(), jTextField_Destino.getText()) == 1){
                viagem03.setVisible(true);
            }
            if(user.validarViagem(jTextField_Origem.getText(), jTextField_Destino.getText()) == 2){
                viagem01.setVisible(true);
            }
            if(user.validarViagem(jTextField_Origem.getText(), jTextField_Destino.getText()) == 3){
                viagem02.setVisible(true);
            }
        }
        
            if(flag == 1){//1 == não
                jTextField_Origem.setText("");
                jTextField_Destino.setText("");
                jTextField_CupomD.setText("");
                jTextField_Origem.requestFocus();
            }
    }//GEN-LAST:event_jToggleButton_BuscarActionPerformed

    private void jTextField_OrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_OrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OrigemActionPerformed

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // TODO add your handling code here:
        frmMenuSelecaoVendaCadastros selecaoVendaCadastros = new frmMenuSelecaoVendaCadastros();
        selecaoVendaCadastros.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuInfViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuInfViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuInfViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuInfViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuInfViagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JComboBox<String> jComboBox_Ano;
    private javax.swing.JComboBox<String> jComboBox_Ano1;
    private javax.swing.JComboBox<String> jComboBox_Dia;
    private javax.swing.JComboBox<String> jComboBox_Dia1;
    private javax.swing.JComboBox<String> jComboBox_Mes;
    private javax.swing.JComboBox<String> jComboBox_Mes1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Ano;
    private javax.swing.JLabel jLabel_Ano1;
    private javax.swing.JLabel jLabel_CupomD;
    private javax.swing.JLabel jLabel_DataIda;
    private javax.swing.JLabel jLabel_DataVolta;
    private javax.swing.JLabel jLabel_Destino;
    private javax.swing.JLabel jLabel_Dia;
    private javax.swing.JLabel jLabel_Dia1;
    private javax.swing.JLabel jLabel_Mes;
    private javax.swing.JLabel jLabel_Mes1;
    private javax.swing.JLabel jLabel_Origem;
    private javax.swing.JTextField jTextField_CupomD;
    private javax.swing.JTextField jTextField_Destino;
    private javax.swing.JTextField jTextField_Origem;
    private javax.swing.JToggleButton jToggleButton_Buscar;
    // End of variables declaration//GEN-END:variables
}
