/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

import static java.awt.Frame.NORMAL;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class frmMenuSelecaoViagem03 extends javax.swing.JFrame {

    frmMenuAssentos03_Rota_01 enviaTexto;
    
    frmMenuAssentos03_Rota_01 enviaPreco;
    
    frmMenuAssentos03_Rota_01 enviaInf;
    //frmMenuInformacoesP enviaInf;
    
    
    public double preco;
    /**
     * Creates new form frmMenuSelecaoViagem03
     */
    public frmMenuSelecaoViagem03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton_SelecionarViagem1 = new javax.swing.JButton();
        jLabel_Empresa = new javax.swing.JLabel();
        jLabel_Trecho = new javax.swing.JLabel();
        jLabel_Horario = new javax.swing.JLabel();
        jLabel_Tarifa = new javax.swing.JLabel();
        jLabel_EmpresaMuffin = new javax.swing.JLabel();
        jLabel_TrechoSaoLuis = new javax.swing.JLabel();
        jLabel_TrechoSaoPaulo = new javax.swing.JLabel();
        jLabel_ClasseExecutivo = new javax.swing.JLabel();
        jButton_ConvencionalI = new javax.swing.JButton();
        jLabel_Horario09002DIAS = new javax.swing.JLabel();
        jRadioButton_Ida = new javax.swing.JRadioButton();
        jRadioButton_IdaVolta = new javax.swing.JRadioButton();
        jButton_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_SelecionarViagem1.setText("Selecionar");
        jButton_SelecionarViagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarViagem1ActionPerformed(evt);
            }
        });

        jLabel_Empresa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Empresa.setText("EMPRERSA");

        jLabel_Trecho.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Trecho.setText("TRECHO/CLASSE");

        jLabel_Horario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Horario.setText("HORÁRIO/DURAÇÃO");

        jLabel_Tarifa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Tarifa.setText("TARIFA");

        jLabel_EmpresaMuffin.setFont(new java.awt.Font("Futura CondensedLight", 3, 24)); // NOI18N
        jLabel_EmpresaMuffin.setText("MUFFIN");

        jLabel_TrechoSaoLuis.setText("SAO LUIS - MA");

        jLabel_TrechoSaoPaulo.setText("SÃO PAULO - SP");

        jLabel_ClasseExecutivo.setText("EXECUTIVO");

        jButton_ConvencionalI.setText("i");
        jButton_ConvencionalI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConvencionalIActionPerformed(evt);
            }
        });

        jLabel_Horario09002DIAS.setText("09:00 - 12:05 (2 DIAS)");

        buttonGroup1.add(jRadioButton_Ida);
        jRadioButton_Ida.setText("IDA: R$ 452,61");

        buttonGroup1.add(jRadioButton_IdaVolta);
        jRadioButton_IdaVolta.setText("IDA E VOLTA: R$ 905,22");

        jButton_Voltar.setText("Voltar");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_EmpresaMuffin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TrechoSaoLuis)
                            .addComponent(jLabel_TrechoSaoPaulo))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel_ClasseExecutivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ConvencionalI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButton_Ida))
                            .addComponent(jRadioButton_IdaVolta))
                        .addGap(34, 34, 34)
                        .addComponent(jButton_SelecionarViagem1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel_Trecho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                                .addComponent(jLabel_Horario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Voltar)
                                    .addComponent(jLabel_Horario09002DIAS))))
                        .addGap(138, 138, 138)
                        .addComponent(jLabel_Tarifa)
                        .addGap(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Horario)
                        .addComponent(jLabel_Tarifa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Trecho)
                        .addComponent(jLabel_Empresa)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_EmpresaMuffin)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_ClasseExecutivo)
                                .addComponent(jButton_ConvencionalI)
                                .addComponent(jLabel_Horario09002DIAS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_TrechoSaoLuis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_TrechoSaoPaulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Voltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_SelecionarViagem1)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButton_Ida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_IdaVolta)
                                .addGap(23, 23, 23))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // TODO add your handling code here:
        frmMenuSelecaoViagem03 viagem03 = new frmMenuSelecaoViagem03();
        dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    private void jButton_ConvencionalIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConvencionalIActionPerformed
        // TODO add your handling code here:
        frmMenuExecutivo executivo = new frmMenuExecutivo();
        executivo.setVisible(true);
    }//GEN-LAST:event_jButton_ConvencionalIActionPerformed

    private void jButton_SelecionarViagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarViagem1ActionPerformed
        // TODO add your handling code here:
        enviaPreco = new frmMenuAssentos03_Rota_01();
        enviaTexto = new frmMenuAssentos03_Rota_01();
        enviaInf = new frmMenuAssentos03_Rota_01();
        String buttonText1 = new String();
        if(jRadioButton_Ida.isSelected() == true){
            buttonText1 = jRadioButton_Ida.getText();
            enviaTexto.recebendoV1(jRadioButton_Ida.getText());
            preco = 452.61;
            enviaPreco.recebendoPreco1(preco);
            enviaInf.receberEmpresa(jLabel_EmpresaMuffin.getText());
            enviaInf.receberRota(jLabel_TrechoSaoLuis.getText(), jLabel_TrechoSaoPaulo.getText());
            enviaInf.receberTipo(jLabel_ClasseExecutivo.getText());
            enviaInf.receberHorario(jLabel_Horario09002DIAS.getText());
            enviaInf.receberTarifa(jRadioButton_Ida.getText());
        }else if(jRadioButton_IdaVolta.isSelected() == true){
            buttonText1 = jRadioButton_IdaVolta.getText();
            enviaTexto.recebendoV1(jRadioButton_IdaVolta.getText());
            preco = 905.22;
            enviaPreco.recebendoPreco1(preco);
            enviaInf.receberEmpresa(jLabel_EmpresaMuffin.getText());
            enviaInf.receberRota(jLabel_TrechoSaoLuis.getText(), jLabel_TrechoSaoPaulo.getText());
            enviaInf.receberTipo(jLabel_ClasseExecutivo.getText());
            enviaInf.receberHorario(jLabel_Horario09002DIAS.getText());
            enviaInf.receberTarifa(jRadioButton_IdaVolta.getText());
        }
        int flag = JOptionPane.showConfirmDialog(null, "Empresa: "+jLabel_EmpresaMuffin.getText()+
                "\nTrecho/Classe: "+jLabel_TrechoSaoLuis.getText()+" -> "+jLabel_TrechoSaoPaulo.getText()+" / "+jLabel_ClasseExecutivo.getText()+
                "\nHorário/Duração: "+jLabel_Horario09002DIAS.getText()+
                "\nTarifa: "+ buttonText1,"Confirmar seleção!", NORMAL);
        if(jRadioButton_Ida.isSelected() == true || jRadioButton_IdaVolta.isSelected() == true){
            if(flag == 0){//0 == sim
                //frmMenuAssentos01_Rota_03 assentos01 = new frmMenuAssentos01_Rota_03();
                //assentos01.setVisible(true);
                enviaInf.setVisible(true);
            }

            if(flag == 1){//1 == não
                jButton_SelecionarViagem1.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "TARIFA NÃO SELECIONADA!");
            jRadioButton_Ida.requestFocus();
        }    
    }//GEN-LAST:event_jButton_SelecionarViagem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuSelecaoViagem03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_ConvencionalI;
    private javax.swing.JButton jButton_SelecionarViagem1;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel_ClasseExecutivo;
    private javax.swing.JLabel jLabel_Empresa;
    private javax.swing.JLabel jLabel_EmpresaMuffin;
    private javax.swing.JLabel jLabel_Horario;
    private javax.swing.JLabel jLabel_Horario09002DIAS;
    private javax.swing.JLabel jLabel_Tarifa;
    private javax.swing.JLabel jLabel_Trecho;
    private javax.swing.JLabel jLabel_TrechoSaoLuis;
    private javax.swing.JLabel jLabel_TrechoSaoPaulo;
    private javax.swing.JRadioButton jRadioButton_Ida;
    private javax.swing.JRadioButton jRadioButton_IdaVolta;
    // End of variables declaration//GEN-END:variables
}
