/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c_v_passagens;

import static java.awt.Frame.NORMAL;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class frmMenuSelecaoViagem02 extends javax.swing.JFrame {

    frmMenuAssentos02_Rora_01 enviaTexto;
    frmMenuAssentos02_Rota_02 enviaTexto2;
    
    frmMenuAssentos02_Rora_01 enviaPreco;
    frmMenuAssentos02_Rota_02 enviaPreco2;
    
    frmMenuAssentos02_Rora_01 enviaInf;
    frmMenuAssentos02_Rota_02 enviaInf2;
    public double preco;
    /**
     * Creates new form frmMenuSelecaoViagem02
     */
    public frmMenuSelecaoViagem02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton_SelecionarViagem2 = new javax.swing.JButton();
        jButton_SelecionarViagem1 = new javax.swing.JButton();
        jLabel_Empresa = new javax.swing.JLabel();
        jLabel_Trecho = new javax.swing.JLabel();
        jLabel_Horario = new javax.swing.JLabel();
        jLabel_Tarifa = new javax.swing.JLabel();
        jLabel_EmpresaMuffin = new javax.swing.JLabel();
        jLabel_TrechoSaoLuis = new javax.swing.JLabel();
        jLabel_TrechoTeresina = new javax.swing.JLabel();
        jLabel_ClasseCovencional = new javax.swing.JLabel();
        jButton_ConvencionalI = new javax.swing.JButton();
        jLabel_Horario0700 = new javax.swing.JLabel();
        jLabel_Horario1 = new javax.swing.JLabel();
        jLabel_Tarifa1 = new javax.swing.JLabel();
        jLabel_TrechoSaoLuis1 = new javax.swing.JLabel();
        jLabel_TrechoTeresina1 = new javax.swing.JLabel();
        jLabel_ClasseConexao = new javax.swing.JLabel();
        jButton_ConexaoI = new javax.swing.JButton();
        jLabel_Horario0900 = new javax.swing.JLabel();
        jLabel_Trecho1 = new javax.swing.JLabel();
        jLabel_EmpresaMuffin1 = new javax.swing.JLabel();
        jLabel_Empresa1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton_Ida = new javax.swing.JRadioButton();
        jRadioButton_IdaVolta = new javax.swing.JRadioButton();
        jRadioButton_Ida1 = new javax.swing.JRadioButton();
        jRadioButton_IdaVolta1 = new javax.swing.JRadioButton();
        jButton_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_SelecionarViagem2.setText("Selecionar");
        jButton_SelecionarViagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarViagem2ActionPerformed(evt);
            }
        });

        jButton_SelecionarViagem1.setText("Selecionar");
        jButton_SelecionarViagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarViagem1ActionPerformed(evt);
            }
        });

        jLabel_Empresa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Empresa.setText("EMPRERSA");

        jLabel_Trecho.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Trecho.setText("TRECHO/CLASSE");

        jLabel_Horario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Horario.setText("HORÁRIO/DURAÇÃO");

        jLabel_Tarifa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Tarifa.setText("TARIFA");

        jLabel_EmpresaMuffin.setFont(new java.awt.Font("Futura CondensedLight", 3, 24)); // NOI18N
        jLabel_EmpresaMuffin.setText("MUFFIN");

        jLabel_TrechoSaoLuis.setText("SAO LUIS (MA)");

        jLabel_TrechoTeresina.setText("TERESINA (PI)");

        jLabel_ClasseCovencional.setText("CONVENCIONAL");

        jButton_ConvencionalI.setText("i");
        jButton_ConvencionalI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConvencionalIActionPerformed(evt);
            }
        });

        jLabel_Horario0700.setText("07:00 - 15:44");

        jLabel_Horario1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Horario1.setText("HORÁRIO/DURAÇÃO");

        jLabel_Tarifa1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Tarifa1.setText("TARIFA");

        jLabel_TrechoSaoLuis1.setText("SAO LUIS (MA)");

        jLabel_TrechoTeresina1.setText("TERESINA (PI)");

        jLabel_ClasseConexao.setText("CONEXÃO");

        jButton_ConexaoI.setText("i");
        jButton_ConexaoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConexaoIActionPerformed(evt);
            }
        });

        jLabel_Horario0900.setText("09:00 - 17:12");

        jLabel_Trecho1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Trecho1.setText("TRECHO/CLASSE");

        jLabel_EmpresaMuffin1.setFont(new java.awt.Font("Futura CondensedLight", 3, 24)); // NOI18N
        jLabel_EmpresaMuffin1.setText("MUFFIN");

        jLabel_Empresa1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Empresa1.setText("EMPRERSA");

        buttonGroup1.add(jRadioButton_Ida);
        jRadioButton_Ida.setText("IDA: R$ 106,80");

        buttonGroup1.add(jRadioButton_IdaVolta);
        jRadioButton_IdaVolta.setText("IDA E VOLTA: R$ 213,60");

        buttonGroup2.add(jRadioButton_Ida1);
        jRadioButton_Ida1.setText("IDA: R$ 91,28");

        buttonGroup2.add(jRadioButton_IdaVolta1);
        jRadioButton_IdaVolta1.setText("IDA E VOLTA: R$ 182,56");

        jButton_Voltar.setText("Voltar");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_EmpresaMuffin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_EmpresaMuffin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_TrechoSaoLuis)
                                    .addComponent(jLabel_TrechoTeresina))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel_ClasseCovencional)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ConvencionalI)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel_Horario0700)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Ida)
                                        .addGap(66, 66, 66))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton_IdaVolta)
                                        .addGap(39, 39, 39)))
                                .addComponent(jButton_SelecionarViagem1)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Trecho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Horario)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel_Tarifa)
                                .addGap(198, 198, 198))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_TrechoSaoLuis1)
                                    .addComponent(jLabel_TrechoTeresina1))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel_ClasseConexao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ConexaoI)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel_Horario0900)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton_Ida1)
                                        .addGap(64, 64, 64))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton_IdaVolta1)
                                        .addGap(33, 33, 33)))
                                .addComponent(jButton_SelecionarViagem2)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_Empresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Trecho1)
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Voltar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Horario1)
                                .addGap(149, 149, 149)
                                .addComponent(jLabel_Tarifa1)))
                        .addGap(193, 193, 193))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Empresa)
                        .addComponent(jLabel_Trecho))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Tarifa)
                        .addComponent(jLabel_Horario)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_Ida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_IdaVolta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_ClasseCovencional)
                                            .addComponent(jButton_ConvencionalI)
                                            .addComponent(jLabel_Horario0700))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_TrechoSaoLuis)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel_TrechoTeresina)))
                                    .addComponent(jLabel_EmpresaMuffin))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton_SelecionarViagem1)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_Horario1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Empresa1)
                            .addComponent(jLabel_Trecho1)))
                    .addComponent(jLabel_Tarifa1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel_EmpresaMuffin1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_ClasseConexao)
                                        .addComponent(jButton_ConexaoI)
                                        .addComponent(jLabel_Horario0900))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_TrechoSaoLuis1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_TrechoTeresina1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton_Ida1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_IdaVolta1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jButton_SelecionarViagem2)
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // TODO add your handling code here:
        frmMenuSelecaoViagem02 viagem02 = new frmMenuSelecaoViagem02();
        dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    private void jButton_ConvencionalIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConvencionalIActionPerformed
        // TODO add your handling code here:
        frmMenuConvencional convencional = new frmMenuConvencional();
        convencional.setVisible(true);
    }//GEN-LAST:event_jButton_ConvencionalIActionPerformed

    private void jButton_ConexaoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConexaoIActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_ConexaoIActionPerformed

    private void jButton_SelecionarViagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarViagem1ActionPerformed
        // TODO add your handling code here:
        enviaInf = new frmMenuAssentos02_Rora_01();
        enviaPreco = new frmMenuAssentos02_Rora_01();
        enviaTexto = new frmMenuAssentos02_Rora_01();
        String buttonText1 = new String();
        if(jRadioButton_Ida.isSelected() == true){
            buttonText1 = jRadioButton_Ida.getText();
            enviaTexto.recebendoV1(jRadioButton_Ida.getText());
            preco = 106.80;
            enviaPreco.recebendoPreco1(preco);
            enviaInf.receberEmpresa(jLabel_EmpresaMuffin.getText());
            enviaInf.receberRota(jLabel_TrechoSaoLuis.getText(), jLabel_TrechoTeresina.getText());
            enviaInf.receberTipo(jLabel_ClasseCovencional.getText());
            enviaInf.receberHorario(jLabel_Horario0700.getText());
            enviaInf.receberTarifa(jRadioButton_Ida.getText());
        }else if(jRadioButton_IdaVolta.isSelected() == true){
            buttonText1 = jRadioButton_IdaVolta.getText();
            enviaTexto.recebendoV1(jRadioButton_IdaVolta.getText());
            preco = 213.60;
            enviaPreco.recebendoPreco1(preco);
            enviaInf.receberEmpresa(jLabel_EmpresaMuffin.getText());
            enviaInf.receberRota(jLabel_TrechoSaoLuis.getText(), jLabel_TrechoTeresina.getText());
            enviaInf.receberTipo(jLabel_ClasseCovencional.getText());
            enviaInf.receberHorario(jLabel_Horario0700.getText());
            enviaInf.receberTarifa(jRadioButton_IdaVolta.getText());
        }
        int flag = JOptionPane.showConfirmDialog(null, "Empresa: "+jLabel_EmpresaMuffin.getText()+
                "\nTrecho/Classe: "+jLabel_TrechoSaoLuis.getText()+" -> "+jLabel_TrechoTeresina.getText()+" / "+jLabel_ClasseCovencional.getText()+
                "\nHorário/Duração: "+jLabel_Horario0700.getText()+
                "\nTarifa: "+ buttonText1,"Confirmar seleção!", NORMAL);
        if(jRadioButton_Ida.isSelected() == true || jRadioButton_IdaVolta.isSelected() == true){
            if(flag == 0){//0 == sim
                frmMenuAssentos01_Rota_02 assentos01 = new frmMenuAssentos01_Rota_02();
                //assentos01.setVisible(true);
                enviaInf.setVisible(true);
                //enviaTexto.setVisible(true);
            }

            if(flag == 1){//1 == não
                jButton_SelecionarViagem1.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "TARIFA NÃO SELECIONADA!");
            jRadioButton_Ida.requestFocus();
        }    
    }//GEN-LAST:event_jButton_SelecionarViagem1ActionPerformed

    private void jButton_SelecionarViagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarViagem2ActionPerformed
        // TODO add your handling code here:
        enviaInf2 = new frmMenuAssentos02_Rota_02();
        enviaPreco2 = new frmMenuAssentos02_Rota_02();
        enviaTexto2 = new frmMenuAssentos02_Rota_02();
        String buttonText2 = new String();
        if(jRadioButton_Ida1.isSelected() == true){
            buttonText2 = jRadioButton_Ida1.getText();
            enviaTexto2.recebendoV2(jRadioButton_Ida1.getText());
            preco = 91.28;
            enviaPreco2.recebendoPreco2(preco);
            enviaInf2.receberEmpresa(jLabel_EmpresaMuffin1.getText());
            enviaInf2.receberRota(jLabel_TrechoSaoLuis1.getText(), jLabel_TrechoTeresina1.getText());
            enviaInf2.receberTipo(jLabel_ClasseConexao.getText());
            enviaInf2.receberHorario(jLabel_Horario0900.getText());
            enviaInf2.receberTarifa(jRadioButton_Ida1.getText());
        }else if(jRadioButton_IdaVolta1.isSelected() == true){
            buttonText2 = jRadioButton_IdaVolta1.getText();
            enviaTexto2.recebendoV2(jRadioButton_IdaVolta1.getText());
            preco = 182.56;
            enviaPreco2.recebendoPreco2(preco);
            enviaInf2.receberEmpresa(jLabel_EmpresaMuffin1.getText());
            enviaInf2.receberRota(jLabel_TrechoSaoLuis1.getText(), jLabel_TrechoTeresina1.getText());
            enviaInf2.receberTipo(jLabel_ClasseConexao.getText());
            enviaInf2.receberHorario(jLabel_Horario0900.getText());
            enviaInf2.receberTarifa(jRadioButton_IdaVolta1.getText());
        }
        int flag = JOptionPane.showConfirmDialog(null, "Empresa: "+jLabel_EmpresaMuffin1.getText()+
                "\nTrecho/Classe: "+jLabel_TrechoSaoLuis1.getText()+" -> "+jLabel_TrechoTeresina1.getText()+" / "+jLabel_ClasseConexao.getText()+
                "\nHorário/Duração: "+jLabel_Horario0900.getText()+
                "\nTarifa: "+ buttonText2,"Confirmar seleção!", NORMAL);
        if(jRadioButton_Ida1.isSelected() == true || jRadioButton_IdaVolta1.isSelected() == true){
            if(flag == 0){//0 == sim
                frmMenuAssentos02_Rota_02 assentos02 = new frmMenuAssentos02_Rota_02();
                //assentos02.setVisible(true);
                //enviaTexto2.setVisible(true);
                enviaInf2.setVisible(true);
            }

            if(flag == 1){//1 == não
                jButton_SelecionarViagem2.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "TARIFA NÃO SELECIONADA!");
            jRadioButton_Ida1.requestFocus();
        }    
    }//GEN-LAST:event_jButton_SelecionarViagem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuSelecaoViagem02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuSelecaoViagem02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton_ConexaoI;
    private javax.swing.JButton jButton_ConvencionalI;
    private javax.swing.JButton jButton_SelecionarViagem1;
    private javax.swing.JButton jButton_SelecionarViagem2;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel_ClasseConexao;
    private javax.swing.JLabel jLabel_ClasseCovencional;
    private javax.swing.JLabel jLabel_Empresa;
    private javax.swing.JLabel jLabel_Empresa1;
    private javax.swing.JLabel jLabel_EmpresaMuffin;
    private javax.swing.JLabel jLabel_EmpresaMuffin1;
    private javax.swing.JLabel jLabel_Horario;
    private javax.swing.JLabel jLabel_Horario0700;
    private javax.swing.JLabel jLabel_Horario0900;
    private javax.swing.JLabel jLabel_Horario1;
    private javax.swing.JLabel jLabel_Tarifa;
    private javax.swing.JLabel jLabel_Tarifa1;
    private javax.swing.JLabel jLabel_Trecho;
    private javax.swing.JLabel jLabel_Trecho1;
    private javax.swing.JLabel jLabel_TrechoSaoLuis;
    private javax.swing.JLabel jLabel_TrechoSaoLuis1;
    private javax.swing.JLabel jLabel_TrechoTeresina;
    private javax.swing.JLabel jLabel_TrechoTeresina1;
    private javax.swing.JRadioButton jRadioButton_Ida;
    private javax.swing.JRadioButton jRadioButton_Ida1;
    private javax.swing.JRadioButton jRadioButton_IdaVolta;
    private javax.swing.JRadioButton jRadioButton_IdaVolta1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
